### ISSUE TITLE
对于地图数据解析的一些疑问

### ISSUE THREAD

**Issue by qjzcj2008** [GachaSalt/ArkToolDemo#3]
大佬开发的这个舟游工具真的非常好用，感谢大佬付出的辛苦。
地图查看功能在新版本可能是由于不可抗力或者是风险规避的原因下线了，有些可惜。
地图查看功能真的非常方便，特别是可以给我在自律漏怪的时候对照，找出翻车原因，或者是可以在打本演习之前就可以对这张图的敌人信息有所了解，帮助我规划打法...总之真的提供了极大的便利
我刚巧保存过一份还有地图查看功能版本（1.6.1.0）的webpack打包后的代码，于是出于希望能对地图查看功能进行维护添加新地图数据的目的，我对这份代码进行了一些逆向工作，现在已经可以通过对mapList的编辑进而添加地图了
![image](https://user-images.githubusercontent.com/16514953/62421444-7d1ec000-b6d4-11e9-97e9-59b3135487c4.png)
但对于详细的地图数据似乎还有一些问题，由打包后的代码解码来到地图数据和直接由游戏解包得到的数据有一些差别，我试着直接导入解包得到的原始数据会出错
![image](https://user-images.githubusercontent.com/16514953/62421493-26fe4c80-b6d5-11e9-94cc-bccd67e0934b.png)
工具中解码得到的地图文件和原始数据有着一些差别与对应关系，我想这个大概是由于webpack打包压缩和（或）大佬的优化引起的，无用数据被删除了，可以复用的数据如mapData下的tiles被单独存放
![image](https://user-images.githubusercontent.com/16514953/62421518-88beb680-b6d5-11e9-962b-8cfb71cd9e04.png)
options下存放着地图的基本信息，runes下则对应突袭数据，routes下对应敌方路径，waves对应出兵信息，map应该来源自原始数据mapData下的map但我无法找到具体的对应转换方法，enemy下应该存放的是敌方数据
除了options与原始数据完全一致，其他的数据是对应的原始数据去掉了key name转换过来的，map下的数据转换方式不太清楚，enemy下的数据感觉对应也有些混乱，不是很清楚，而且enemy下的敌人id被替换了，但我还没有找到对应关系
不知道大佬能不能给一些提示或者是帮助，或者是能提供一份ver.1.6.1.0的sourcemap？我仅在本地部署自用可以吗？
附上逆向得到的level_main_00-01
`{"map":"yyyyyyyyy ysssssssy y999s999e o9s99999y ysssssssy yyyyyyyyy","token":[],"routes":[null,null,[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],[0,[2,8],[3,0],[[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]],null,[0,[2,8],[3,0],[[0,0.0,2,7,0.0,0.0],[1,3.0,0,0,0.0,0.0],[0,0.0,3,3,0.0,0.0],[0,0.0,2,3,0.0,0.0],[0,0.0,2,1,0.0,0.0],[0,0.0,3,1,0.0,0.0]]]],"waves":[[0.0,0.0,-1.0,null,[[0.0,[[2,"obt/tutorial/level/main_00-01",1,0.0,1.0,0,false,false]],null],[2.0,[[5,0,1,3.0,1.0,1,true,false],[0,0,1,3.0,1.0,2,true,false]],null],[8.0,[[0,0,2,3.0,2.0,3,true,false]],null],[8.0,[[0,0,2,3.0,0.7,4,true,false],[0,0,1,8.0,1.0,5,false,false]],null],[8.0,[[0,0,2,3.0,0.7,6,true,false],[0,0,2,10.0,0.7,7,false,false]],null],[8.0,[[5,10,1,3.0,1.0,8,true,false],[0,10,1,3.0,1.0,9,true,false]],null]]]],"enemy":[[1,0,0,null],[1,10,0,[null,null,null,[null,null,30,null,null,null,null,null,null,null,null,null,null,null,null,null,null],null,null,null,null,null]]],"options":{"characterLimit":8,"maxLifePoint":20,"initialCost":10,"maxCost":99,"costIncreaseTime":1.0,"moveMultiplier":0.5,"steeringEnabled":true,"isTrainingLevel":false,"functionDisableMask":0},"globalBuffs":[],"runes":[["gbuff_lifepoint",2,1023,3,[{"key":"value","value":1.0,"valueStr":null}]],["ebuff_attribute",2,1023,3,[{"key":"atk","value":1.2,"valueStr":null},{"key":"def","value":1.2,"valueStr":null},{"key":"max_hp","value":1.2,"valueStr":null}]],["cbuff_cost_recovery",2,1023,3,[{"key":"scale","value":99999.0,"valueStr":null}]]]}`

**Comment by GachaSalt** [comment]
地图信息经过大幅缩水，所以套用原始地图数据已经没有可行性。
个人使用，可查看该链接。@qjzcj2008
https://cl1p.net/cvbdywwclq

**Comment by Prurite** [comment]
能也给我一份吗（个人使用）

**Comment by GachaSalt** [comment]
@Prurite 
https://pastebin.com/2JEGxNxD

**Comment by Prurite** [comment]
感谢。另外现在好像做这种项目的人比较多啊，比如 https://map.ark-nights.com/map
