### ISSUE TITLE
想请教一下大佬关于「仓库识别材料」这个功能的大概思路

### ISSUE THREAD

**Issue by Metatronwings** [GachaSalt/ArkToolDemo#5]

**Comment by GachaSalt** [comment]
前端的轻量级匹配可使用dhash和ahash.
如果有做后端可以使用SIFT或者SSIM.

前端OCR可以使用tesseractJS库，但速度较慢。我这里使用了dhash。

**Comment by Metatronwings** [comment]
首先谢谢大佬的回复。
我自己最近有在试着开发一个安卓端的仓库识别，目前使用 opencv 中的 HoughCircles 函数来识别出材料区块。虽然准确度还可以，不过速度实在比较慢。即便是缩放到了 480p 的截图也要大概 5-6s 出结果（模拟器运行）。不知道大佬对这个问题有没有一些思路可以分享一下？

发现再降低一下分辨率就好了……240p 的坐标及半径乘系数映射到原图像，精度也还可以

**Comment by GachaSalt** [comment]
材料图标是网格排列的，所以可用计算量小的算法如findContours捕捉可能的识别框，再进行数据清洗和聚类获得全体图标的位置和尺寸。

**Comment by Metatronwings** [comment]
啊……突然想到其实可以只去识别左上角 2x2 的材料位置，其他材料的位置通过间接计算就可以得到
