### ISSUE TITLE
The whole page is gone when clicking the 'calculate' button

### ISSUE THREAD

**Issue by Prurite** [GachaSalt/ArkToolDemo#6]
video here 

[2020-03-07 09-44-42.zip](https://github.com/GachaSalt/ArkToolDemo/files/4301267/2020-03-07.09-44-42.zip)

**Comment by GachaSalt** [comment]
@Prurite 感谢反馈问题。暂时没找到问题的具体原因，不知道bug是否在同一个浏览器上一直出现？
目前修复了一些其他bug & 优化了部分代码，如果还有问题请反馈给我，我会不断跟进。

**Comment by Prurite** [comment]
Issue continues.

**Comment by Prurite** [comment]
New video here, seem problems with editing/purestream

1st time calculate: normal
Added Purestream & 2nd time calculate: normal
Edited Purestream & 3rd time calculte: fail

[2020-03-14 08-18-10.zip](https://github.com/GachaSalt/ArkToolDemo/files/4332114/2020-03-14.08-18-10.zip)

@GachaSalt Consider reopen this issue?

**Comment by GachaSalt** [comment]
It is now found that this problem may be caused by unexpected results of Arkplanner.
The return of Arkplanner will be handled more carefully and the issue should have been resolved.
@Prurite
