### ISSUE TITLE
角色查看界面不能正常查看技能

### ISSUE THREAD

**Issue by MysticEEEE** [GachaSalt/ArkToolDemo#7]
只能查看1级技能的数据，不能查看之后的，技能升级材料也查看不了。
整个面板都不动了，维持在1级技能的状态。
我这边是换了浏览器也同样的问题，不知道大家有遇到和我一样的问题了吗？

**Comment by GachaSalt** [comment]
@MysticEEEE 感谢反馈问题。是网站存在的bug，现已修复（v1.6.9.2）。
